<a href="https://colab.research.google.com/github/mredelis/CAP4453-Robot-Vision-Spr23/blob/main/RV_HW2_Calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np

sigma = 1.4
kernel = []
new_kernel = []

def gaussian(x: int):
  return (1 / ((2 * math.pi)**0.5 * sigma)) * math.e**(- x**2 / ( 2 * sigma**2)) 

sum = 0
for x in range (-3, 4):
  kernel.append(round(gaussian(x), 3))

print("Original Kernel Float Values")
print(kernel)
print()

mat11 = np.matrix(kernel)
mat22 = mat11.reshape(-1,1)

print("Row vector with floats")
print(mat11)
print()

print("Column vector with floats")
print(mat22)
print()

for i in range(len(kernel)):
  kernel[i] = round(kernel[i] * 64)

print("Kernel Divided by 1/64")
print(kernel)
print()

new_res = np.matmul(mat22, mat11)
print("Matrix multiplication with floats *********************************")
print(new_res)
print()

new_res64 = np.around(64**2 * new_res)
print("Matrix multiplication with floats multiplied by 64^2**************")
print(new_res64)
print()

mat1 = np.matrix(kernel)
mat2 = mat1.T
res = np.matmul(mat2, mat1)

print("Multiplying just integer part of the row and column vectors\n")
print("Mat1")
print(mat1)
print()
print("Mat2")
print(mat2)
print()
print(res)
print()

original = np.matrix([[0, 0, 0, 0, 0, 0 , 0],
                     [0, 0, 0, 0, 0, 0 , 0],
                     [0, 0, 0, 0, 0, 0 , 0],
                     [0, 0, 0, 2, 0, 0 , 0],
                     [0, 0, 0, 0, 0, 0 , 0],
                     [0, 0, 0, 0, 0, 0 , 0],
                     [0, 0, 0, 0, 0, 0 , 0]])

print(original)
print()

new_gaussian = 1/4096 * res
print("New Gaussian filter should be ~ to Matrix multiplication with floats *********************************\n")
print(new_gaussian)
print()

print("2 Times Original Image less Gaussian blur\n")
res2 = np.subtract(original, new_gaussian)
print(res2)
print()

print("ROUNDED -> 2 Times Original Image less Gaussian blur\n")
res2_rounded = np.round(res2, 3)
print(res2_rounded)
print()

Original Kernel Float Values
[0.029, 0.103, 0.221, 0.285, 0.221, 0.103, 0.029]

Row vector with floats
[[0.029 0.103 0.221 0.285 0.221 0.103 0.029]]

Column vector with floats
[[0.029]
 [0.103]
 [0.221]
 [0.285]
 [0.221]
 [0.103]
 [0.029]]

Kernel Divided by 1/64
[2, 7, 14, 18, 14, 7, 2]

Matrix multiplication with floats *********************************
[[0.000841 0.002987 0.006409 0.008265 0.006409 0.002987 0.000841]
 [0.002987 0.010609 0.022763 0.029355 0.022763 0.010609 0.002987]
 [0.006409 0.022763 0.048841 0.062985 0.048841 0.022763 0.006409]
 [0.008265 0.029355 0.062985 0.081225 0.062985 0.029355 0.008265]
 [0.006409 0.022763 0.048841 0.062985 0.048841 0.022763 0.006409]
 [0.002987 0.010609 0.022763 0.029355 0.022763 0.010609 0.002987]
 [0.000841 0.002987 0.006409 0.008265 0.006409 0.002987 0.000841]]

Matrix multiplication with floats multiplied by 64^2**************
[[  3.  12.  26.  34.  26.  12.   3.]
 [ 12.  43.  93. 120.  93.  43.  12.]
 [ 26.  93. 200. 258. 200.  93.  26

In [ ]:
sigma = 1
kernel = []

# Check function againts example online with sigma = 1. Function implementation is right
def gaussian(x: int):
  return (1 / ((2 * math.pi)**0.5 * sigma)) * math.e**(- x**2 / ( 2 * sigma**2)) 

sum = 0
for x in range (-1, 2):
  kernel.append(round(gaussian(x), 3))

print(kernel)

# Divide by 16
for i in range(len(kernel)):
  kernel[i] = round(kernel[i] * 4)

print(kernel)


[0.242, 0.399, 0.242]
[1, 2, 1]
